(define (problem paths)
  (:domain paths-class)
  (:objects puerto - location 
    almacen - location
    fabrica1 fabrica2 - location 
    tren - vehicle 
    contenedor1 contenedor2 contenedor3 contenedor4 contenedor5 contenedor6 contenedor7 contenedor8 - package 
    trenCapacity0 trenCapacity1 trenCapacity2 trenCapacity3 trenCapacity4 - num  
  )
  (:init
    (connected almacen puerto)
    (connected puerto fabrica1)
    (connected fabrica1 fabrica2)
    (connected fabrica2 almacen)
    (connected puerto almacen)
    (connected almacen fabrica2)
    (connected fabrica2 fabrica1)
    (connected fabrica1 puerto)
    (in contenedor1 puerto)
    (in contenedor2 puerto)
    (in contenedor3 puerto)
    (in contenedor4 puerto)
    (in contenedor5 puerto)
    (in contenedor6 puerto)
    (in contenedor7 puerto)
    (in contenedor8 puerto)
    (at tren puerto)
    (capacity tren trenCapacity0)
    (countForwards trenCapacity0 trenCapacity1)
    (countForwards trenCapacity1 trenCapacity2)
    (countForwards trenCapacity2 trenCapacity3)
    (countForwards trenCapacity3 trenCapacity4)
    (countBackwards trenCapacity4 trenCapacity3)
    (countBackwards trenCapacity3 trenCapacity2)
    (countBackwards trenCapacity2 trenCapacity1)
    (countBackwards trenCapacity1 trenCapacity0)
    ; (not(processed contenedor1))
    ; (not (processed contenedor2))
    ; (not (processed contenedor3))
    ; (not (processed contenedor4))
    ; (not (processed contenedor5))
    ; (not (processed contenedor6))
    ; (not (processed contenedor7))
    ; (not (processed contenedor8))
  )
 (:goal 
  (and 
    ; (at tren fabrica1)
    ; (capacity tren trenCapacity4)
    ; (in contenedor1 fabrica2)
    (in contenedor1 almacen)
    (in contenedor2 almacen)
    (in contenedor3 almacen)
  )
    ; (and 
    ;   (processed contenedor1)
    ;   (processed contenedor2)
    ;   (processed contenedor3)
    ;   (processed contenedor4)
    ;   (processed contenedor5)
    ;   (processed contenedor6)
    ;   (processed contenedor7)
    ;   (processed contenedor8)
    ;   (on contenedor1 almacen)
    ;   (on contenedor2 almacen)
    ;   (on contenedor3 almacen)
    ;   (on contenedor4 almacen)
    ;   (on contenedor5 almacen)
    ;   (on contenedor6 almacen)
    ;   (on contenedor7 almacen)
    ;   (on contenedor8 almacen)
    ; )
  )
)