(define (problem paths)
  (:domain paths-class)
  (:objects puerto - location 
    almacen - location
    fabrica1 fabrica2 - location 
    tren - vehicle 
    contenedor1 contenedor2 contenedor3 contenedor4 contenedor5 contenedor6 contenedor7 contenedor8 - package 
    vehCapacity0 vehCapacity1 vehCapacity2 vehCapacity3 vehCapacity4 - numVeh  
    locCapacity0 locCapacity1 locCapacity2 locCapacity3 - numLoc  
  )
  (:init
    ; connecting locations bidirectional 
    (connected almacen puerto)
    (connected puerto fabrica1)
    (connected fabrica1 fabrica2)
    (connected fabrica2 almacen)
    (connected puerto almacen)
    (connected almacen fabrica2)
    (connected fabrica2 fabrica1)
    (connected fabrica1 puerto)
    ; init containers, locations and train
    (in contenedor1 puerto)
    (in contenedor2 puerto)
    (in contenedor3 puerto)
    (in contenedor4 puerto)
    (in contenedor5 puerto)
    (in contenedor6 puerto)
    (in contenedor7 puerto)
    (in contenedor8 puerto)
    (at tren puerto)
    (isPort puerto)
    (not(isPort almacen))
    (not(isPort fabrica1))
    (not(isPort fabrica2))
    ; init capacities
    (capacityVeh tren vehCapacity0)
    (capacityLoc almacen locCapacity0)
    (capacityLoc fabrica1 locCapacity0)
    (capacityLoc fabrica2 locCapacity0)
    ; set max capaticies
    (maxCapacityVeh tren vehCapacity4)
    (maxCapacityLoc almacen locCapacity3)
    (maxCapacityLoc fabrica1 locCapacity2)
    (maxCapacityLoc fabrica2 locCapacity3)
    ; counts for capacities
    (countVeh vehCapacity0 vehCapacity1)
    (countVeh vehCapacity1 vehCapacity2)
    (countVeh vehCapacity2 vehCapacity3)
    (countVeh vehCapacity3 vehCapacity4)
    (countLoc locCapacity0 locCapacity1)
    (countLoc locCapacity1 locCapacity2)
    (countLoc locCapacity2 locCapacity3)
    ; (not(processed contenedor1))
    ; (not (processed contenedor2))
    ; (not (processed contenedor3))
    ; (not (processed contenedor4))
    ; (not (processed contenedor5))
    ; (not (processed contenedor6))
    ; (not (processed contenedor7))
    ; (not (processed contenedor8))
  )
 (:goal 
  (and 
    ; (at tren fabrica1)
    ; (capacityLoc almacen capacity1)
    (in contenedor1 almacen)
    (in contenedor2 almacen)
    (in contenedor3 almacen)
    (in contenedor4 fabrica2)
    (in contenedor5 fabrica2)
    (in contenedor6 fabrica2)
    (in contenedor7 fabrica2)
  )
    ; (and 
    ;   (processed contenedor1)
    ;   (processed contenedor2)
    ;   (processed contenedor3)
    ;   (processed contenedor4)
    ;   (processed contenedor5)
    ;   (processed contenedor6)
    ;   (processed contenedor7)
    ;   (processed contenedor8)
    ;   (on contenedor1 almacen)
    ;   (on contenedor2 almacen)
    ;   (on contenedor3 almacen)
    ;   (on contenedor4 almacen)
    ;   (on contenedor5 almacen)
    ;   (on contenedor6 almacen)
    ;   (on contenedor7 almacen)
    ;   (on contenedor8 almacen)
    ; )
  )
)