(define (problem paths)
  (:domain paths-class)
  (:objects puerto - location 
    almacen - location
    fabrica1 fabrica2 - location 
    tren - vehicle 
    contenedor1 contenedor2 contenedor3 contenedor4 contenedor5 contenedor6 contenedor7 contenedor8 - package 
    vehCapacity0 vehCapacity1 vehCapacity2 vehCapacity3 vehCapacity4 - numVeh  
    locCapacity0 locCapacity1 locCapacity2 locCapacity3 - numLoc  
  )
  (:init
    ; connecting locations bidirectional 
    (connected almacen puerto)
    (connected puerto fabrica1)
    (connected fabrica1 fabrica2)
    (connected fabrica2 almacen)
    (connected puerto almacen)
    (connected almacen fabrica2)
    (connected fabrica2 fabrica1)
    (connected fabrica1 puerto)
    ; init containers, locations and train
    (in contenedor1 puerto)
    (in contenedor2 puerto)
    (in contenedor3 puerto)
    (in contenedor4 puerto)
    (in contenedor5 puerto)
    (in contenedor6 puerto)
    (in contenedor7 puerto)
    (in contenedor8 puerto)
    (at tren puerto)
    (isPort puerto)
    (not(isPort almacen))
    (not(isPort fabrica1))
    (not(isPort fabrica2))
    (isFabric fabrica1)
    (isFabric fabrica2)
    (not(isFabric puerto))
    (not(isFabric almacen))
    (isAlmacen almacen)
    (not(isAlmacen puerto))
    (not(isAlmacen fabrica1))
    (not(isAlmacen fabrica2))
    ; init processed state
    (not(isProcessed contenedor1))
    (not(isProcessed contenedor2))
    (not(isProcessed contenedor3))
    (not(isProcessed contenedor4))
    (not(isProcessed contenedor5))
    (not(isProcessed contenedor6))
    (not(isProcessed contenedor7))
    (not(isProcessed contenedor8))
    (not(isRemoved contenedor1))
    (not(isRemoved contenedor2))
    (not(isRemoved contenedor3))
    (not(isRemoved contenedor4))
    (not(isRemoved contenedor5))
    (not(isRemoved contenedor6))
    (not(isRemoved contenedor7))
    (not(isRemoved contenedor8))
    ; init capacities
    (capacityVeh tren vehCapacity0)
    (capacityLoc almacen locCapacity0)
    (capacityLoc fabrica1 locCapacity0)
    (capacityLoc fabrica2 locCapacity0)
    ; set max capaticies
    (maxCapacityLoc almacen locCapacity3)
    (maxCapacityLoc fabrica1 locCapacity2)
    (maxCapacityLoc fabrica2 locCapacity3)
    ; counts for capacities
    (countVeh vehCapacity0 vehCapacity1)
    (countVeh vehCapacity1 vehCapacity2)
    (countVeh vehCapacity2 vehCapacity3)
    (countVeh vehCapacity3 vehCapacity4)
    (countLoc locCapacity0 locCapacity1)
    (countLoc locCapacity1 locCapacity2)
    (countLoc locCapacity2 locCapacity3)
  )
  (:goal 
    (and 
      (isProcessed contenedor1)
      (isProcessed contenedor2)
      (isProcessed contenedor3)
      (isProcessed contenedor4)
      (isProcessed contenedor5)
      (isProcessed contenedor6)
      (isProcessed contenedor7)
      (isProcessed contenedor8)
      (in contenedor1 almacen)
      (in contenedor2 almacen)
      (in contenedor3 almacen)
      (in contenedor4 almacen)
      (in contenedor5 almacen)
      (in contenedor6 almacen)
      (in contenedor7 almacen)
      (in contenedor8 almacen)
      (isRemoved contenedor1)
      (isRemoved contenedor2)
      (isRemoved contenedor3)
      (isRemoved contenedor4)
      (isRemoved contenedor5)
      (isRemoved contenedor6)
      (isRemoved contenedor7)
      (isRemoved contenedor8)
    )
  )
)